import asyncio
import requests
import json
import os
from agents import (
    Agent,
    ModelSettings,
    Runner,
    function_tool,
    trace,
)
from call_mcp_tool import call_mcp_tool
@function_tool(
    name_override="get_flight_information",
    description_override="Fetch FULL detailed flight information using flexible search criteria",
)
def get_flight_information(
    p_flightid: str | None = None,
    p_airline_code: str | None = None,
    p_flightno: str | None = None,
    p_route: str | None = None,
    p_flightdate: str | None = None,
    p_dept: str | None = None,
    p_arrival: str | None = None,
    p_actype: str | None = None,
    p_flighttype: str | None = None,
    p_eobt: str | None = None,
    p_eibt: str | None = None,
    p_eldt: str | None = None,
    p_status: str | None = None,
) -> str:
    response = call_mcp_tool(
        "get_flight_informations_by_particular_fields",
        {
            "p_flightid": p_flightid,
            "p_airline_code": p_airline_code,
            "p_flightno": p_flightno,
            "p_route": p_route,
            "p_flightdate": p_flightdate,
            "p_dept": p_dept,
            "p_arrival": p_arrival,
            "p_actype": p_actype,
            "p_flighttype": p_flighttype,
            "p_eobt": p_eobt,
            "p_eibt": p_eibt,
            "p_eldt": p_eldt,
            "p_status": p_status,
        },
    )

    flights = json.loads(response["result"]["content"][0]["text"])

    if not flights:
        return "❌ Không tìm thấy chuyến bay phù hợp với tiêu chí tra cứu."

    status_map = {
        "OPN": "🟢 Open – Đang làm thủ tục / boarding",
        "CLS": "🟡 Close – Đã đóng chuyến / đã khởi hành",
        "CNX": "🔴 Canceled – Hủy chuyến",
        "XXX": "⚫ Deleted – Đã xóa khỏi hệ thống",
    }

    results = []
    MAX_FLIGHTS = 5
    flights = flights[:MAX_FLIGHTS]
    for f in flights:
        results.append(
            "✈️ THÔNG TIN CHUYẾN BAY (CHI TIẾT)\n"
            "--------------------------------\n"
            f"🆔 Flight ID: {f.get('Unique identifier generated by the airline system for this flight record')}\n"
            f"🏷️ Hãng bay: {f.get('The airline code is the two-letter IATA prefix of the flight number')}\n"
            f"✈️ Số hiệu chuyến bay: {f.get('The full flight number including airline prefix')}\n"
            f"🗺️ Chặng bay: {f.get('The flight route represented as Origin-Destination')}\n"
            f"📍 Sân bay đi: {f.get('The departure airport code in IATA format (3 letters)')}\n"
            f"📍 Sân bay đến: {f.get('The arrival airport code in IATA format (3 letters)')}\n"
            f"🏠 Base station: {f.get('Base station or operating airport for the flight')}\n"
            f"📅 Ngày bay: {f.get('The scheduled date of the flight in yyyy-MM-dd format')}\n\n"

            "⏰ GIỜ KHAI THÁC\n"
            f"- EIBT (ETA): {f.get('Estimated In-Block Time (EIBT) indicates the estimated time the aircraft will arrive at the gate at the destination')}\n"
            f"- ELDT (Giờ dự kiến hạ cánh): {f.get('Estimated Landing Date and Time (ELDT) is the predicted arrival time at the destination gate')}\n"
            f"- ALDT (Giờ hạ cánh thực tế): {f.get('Actual Landing Date and Time (ALDT) represents the real timestamp when the aircraft landed')}\n"
            f"- AIBT (Giờ vào bãi): {f.get('Actual In-Block Time (AIBT) represents when the aircraft arrives at its parking position at the destination gate')}\n\n"

            "📊 TRẠNG THÁI CHUYẾN BAY\n"
            f"- Trạng thái: {status_map.get(f.get('Current flight status'), f.get('Current flight status'))}\n"
        )
    return "\n\n".join(results)